package com.hnii.jws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * HniiJaxWsServerImplService service = new HniiJaxWsServerImplService();
 * ICjJaxWsServer portType = service.getCjJaxWsServerImplPort();
 * portType.wsRequst(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "HniiJaxWsServerImplService", targetNamespace = "http://service.jws.hnii.com/", wsdlLocation = "WEB-INF/hniiwsdl/hniijaxws.wsdl")
public class HniiJaxWsServerImplService extends Service {

	private final static URL HniiJaxWsServerImplService_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.hnii.jws.client.HniiJaxWsServerImplService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.hnii.jws.client.HniiJaxWsServerImplService.class
					.getResource(".");
			url = new URL(baseUrl, "WEB-INF/hniiwsdl/hniijaxws.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/hniiwsdl/hniijaxws.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		HniiJaxWsServerImplService_WSDL_LOCATION = url;
	}

	public HniiJaxWsServerImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public HniiJaxWsServerImplService() {
		super(HniiJaxWsServerImplService_WSDL_LOCATION, new QName(
				"http://service.jws.hnii.com/", "HniiJaxWsServerImplService"));
	}

	/**
	 * 
	 * @return returns ICjJaxWsServer
	 */
	@WebEndpoint(name = "CjJaxWsServerImplPort")
	public IHniiJaxWsServer getCjJaxWsServerImplPort() {
		return super.getPort(new QName("http://service.jws.hnii.com/",
				"CjJaxWsServerImplPort"), IHniiJaxWsServer.class);
	}

}
